"""add_oauth_fields_to_users

Revision ID: 1f619dddb3fd
Revises: a77ae6b91fcb
Create Date: 2026-02-12 13:08:37.834705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f619dddb3fd'
down_revision: Union[str, Sequence[str], None] = 'a77ae6b91fcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_provider', sa.String(length=20), server_default='email', nullable=False))
    op.add_column('users', sa.Column('provider_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=20), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'provider_id')
    op.drop_column('users', 'auth_provider')
    # ### end Alembic commands ###
