"""initial_security_hardening

Revision ID: a77ae6b91fcb
Revises:
Create Date: 2026-02-12 01:59:41.997433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77ae6b91fcb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacklisted_tokens_jti'), 'blacklisted_tokens', ['jti'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('google_category_key', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('liked_books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('google_book_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('authors', sa.String(length=500), nullable=False),
    sa.Column('thumbnail', sa.String(length=500), nullable=False),
    sa.Column('liked_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'google_book_id', name='uq_user_liked_book')
    )
    op.create_index(op.f('ix_liked_books_google_book_id'), 'liked_books', ['google_book_id'], unique=False)
    op.create_index('ix_liked_books_liked_at', 'liked_books', ['liked_at'], unique=False)
    op.create_index(op.f('ix_liked_books_user_id'), 'liked_books', ['user_id'], unique=False)
    op.create_table('skipped_books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('google_book_id', sa.String(length=50), nullable=False),
    sa.Column('skipped_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'google_book_id', name='uq_user_skipped_book')
    )
    op.create_index(op.f('ix_skipped_books_google_book_id'), 'skipped_books', ['google_book_id'], unique=False)
    op.create_index('ix_skipped_books_skipped_at', 'skipped_books', ['skipped_at'], unique=False)
    op.create_index(op.f('ix_skipped_books_user_id'), 'skipped_books', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skipped_books_user_id'), table_name='skipped_books')
    op.drop_index('ix_skipped_books_skipped_at', table_name='skipped_books')
    op.drop_index(op.f('ix_skipped_books_google_book_id'), table_name='skipped_books')
    op.drop_table('skipped_books')
    op.drop_index(op.f('ix_liked_books_user_id'), table_name='liked_books')
    op.drop_index('ix_liked_books_liked_at', table_name='liked_books')
    op.drop_index(op.f('ix_liked_books_google_book_id'), table_name='liked_books')
    op.drop_table('liked_books')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('categories')
    op.drop_index(op.f('ix_blacklisted_tokens_jti'), table_name='blacklisted_tokens')
    op.drop_table('blacklisted_tokens')
    # ### end Alembic commands ###
