"""add swipe_events and user_preferences tables

Revision ID: dfef822eb8d9
Revises: 07d48e752bae
Create Date: 2026-02-13 00:12:29.129036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfef822eb8d9'
down_revision: Union[str, Sequence[str], None] = '07d48e752bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swipe_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('google_book_id', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('genre', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_swipe_events_created_at', 'swipe_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_swipe_events_google_book_id'), 'swipe_events', ['google_book_id'], unique=False)
    op.create_index('ix_swipe_events_user_action', 'swipe_events', ['user_id', 'action'], unique=False)
    op.create_index(op.f('ix_swipe_events_user_id'), 'swipe_events', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('genre_scores', sa.Text(), nullable=False),
    sa.Column('author_scores', sa.Text(), nullable=False),
    sa.Column('category_scores', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_swipe_events_user_id'), table_name='swipe_events')
    op.drop_index('ix_swipe_events_user_action', table_name='swipe_events')
    op.drop_index(op.f('ix_swipe_events_google_book_id'), table_name='swipe_events')
    op.drop_index('ix_swipe_events_created_at', table_name='swipe_events')
    op.drop_table('swipe_events')
    # ### end Alembic commands ###
